### ISSUE TITLE
Publicar versão 1.0 da aplicação

### ISSUE THREAD

**Issue by ghost** [ederson-torresini/adcipt20222#33]
Requisitos funcionais:

- [x] O jogo deve ser planejado para suportar interação através de várias mídias assíncronas: texto, áudio e vídeo #7.
- [x] O jogo deve ter suporte a mídia síncrona: áudio sobre WebRTC #32.
- [x] Rodar aplicação em servidor virtual #18.
- [x] Persistir dados dos jogadores em banco de dados não relacional #22.
